# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
site:
    owner:
        disque-shortname: yutingzhang
comments: true

gems: [jekyll-paginate]
paginate: 20
paginate_path: "/page:num/"

title: Yuting's Coding Sanctuary
email: yutingzhang@acm.org
description: > # this means to ignore newlines until "baseurl:"
    This Blog is my personal website which documents some of my projects.
    I also post solutions to some competitive programming
    problems here as well.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  yuting-zhang

# Build settings
markdown: kramdown

